### ISSUE TITLE
SA - Create report for ASA12

### ISSUE THREAD

**Issue by guychapman** [St-John-NSW/DEMS#13]
Create Report to pull data required for reporting based on ASA12

**Comment by russelldippy** [comment]
details required in reporting to assist with planning of this export tool

Asa12’s outstanding – per month for last 12 months (rolling)
ASA12’s completed – per month for last 12 months (rolling)
How many clinical patients – per month for last 12 months (rolling)
How many non clinical patients - per month for last 12 months (rolling)
How many event hours - per month for last 12 months (rolling)
How many members event hours - per month for last 12 months (rolling)

These are all taken from the ASA12 form, exported into a spreadsheet.

We will also need to be able to run a report that shows – how many of each treatment has been given, what their discharge advice was ie. ambulance, home, return to event, if a stretcher was used, if a 4wd was used. This data is not for the board reports, it will be used to determine what equipment and fleet we require/is in demand.
