### ISSUE TITLE
Centre Third Sorting of Divisions

### ISSUE THREAD

**Issue by russelldippy** [St-John-NSW/DEMS#32]
When in Main Menu, the centre third of the screen lists all of the divisions that you are an associate member off.  Can that list of divisions below the home division be sorted alphabetically.
Russell DIPPY

**Comment by guychapman** [comment]
In test

**Comment by jhammers15** [comment]
I don't see this in test or production unless I am missing something. See example attached
![dems centre third sort](https://github-cloud.s3.amazonaws.com/assets%2F12591059%2F10958258%2F3dea9e9e-83bc-11e5-86ee-336b42d1e5f6.JPG)

**Comment by guychapman** [comment]
Your division will always come first. All associate divs will be alphabetical

Sent by Outlook<http://taps.io/outlookmobile> for Android



On Wed, Nov 4, 2015 at 6:24 PM -0800, "John Hammersmith" <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't see this in test or production unless I am missing something. See example attached
[dems centre third sort]<https://camo.githubusercontent.com/18f166d77560e8b2ccaf5e0d9943d8aff5042488/68747470733a2f2f6769746875622d636c6f75642e73332e616d617a6f6e6177732e636f6d2f6173736574732532463132353931303539253246313039353832353825324633646561396539652d383362632d313165352d383665652d3333366234326431653566362e4a5047>

-

**Comment by jhammers15** [comment]
O.o
