### ISSUE TITLE
Make all Divsional Events Show in State Region and Other

### ISSUE THREAD

**Issue by jhammers15** [St-John-NSW/DEMS#38]
Guy, We have a mini crisis with event sign up occuring and need to take a fairly drastic action to resolve it. The problem is that we want to operate the whole state in centralized model in so far as all members can see all events and sign up for them. Can DEMS be modified such that every Division Event also gets listed under State/Region/Other. 
As part of this can the default setting for sign up to all events be changed to "waitlisted".
I realise this a fair change from the very Divisional model of DEMS currently but the org has decided this is a neccessary step for us at this time with a priority of 1. Feel free to contact me to discuss.
Regards
John 0413 330 390

**Comment by guychapman** [comment]
Now in test, waiting on feedback

**Comment by jhammers15** [comment]
Guy,

You haven’t implemented this on the production server yet – right?
The reason I ask is that I can see a bunch of events for several Divisions already as per this screenshot:

[cid:image001.png@01D11BAB.10DAB020]


John Hammersmith

Enterprise Solution Architect

P 08 8306 6967   M 0413 330 390
E john.hammersmith@stjohnsa.com.au<mailto:john.hammersmith@stjohnsa.com.au>


St John Ambulance Australia SA Inc.

85 Edmund Ave UNLEY SA 5061
1300 360 455  |  stjohnsa.com.au<http://www.stjohnsa.com.au/>

**Comment by jhammers15** [comment]
Nope. But nothing stopping anyone sharing manually

Sent by Outlook<http://taps.io/outlookmobile> for Android



On Mon, Nov 9, 2015 at 4:59 PM -0800, "John Hammersmith" <John.Hammersmith@stjohnsa.com.au<mailto:John.Hammersmith@stjohnsa.com.au>> wrote:

Guy,

You haven't implemented this on the production server yet - right?
The reason I ask is that I can see a bunch of events for several Divisions already as per this screenshot:

[cid:image001.png@01D11BAB.10DAB020]


John Hammersmith

Enterprise Solution Architect

P 08 8306 6967   M 0413 330 390
E john.hammersmith@stjohnsa.com.au<mailto:john.hammersmith@stjohnsa.com.au>


St John Ambulance Australia SA Inc.

85 Edmund Ave UNLEY SA 5061
1300 360 455  |  stjohnsa.com.au<http://www.stjohnsa.com.au/>
