### ISSUE TITLE
Remove local username/password dialog boxes from SA DEMS login page

### ISSUE THREAD

**Issue by jhammers15** [St-John-NSW/DEMS#39]
St John SA is using Azure AD SSO for DEMS login. The local login dialog boxes are creating confusion for users and the confusion is outweighing the benefit of having the backup of a local username and password facility to use if Azure AD was not working.

**Comment by guychapman** [comment]
Now in test environment. Can override by going to https://<url>:index.php/auth/login/1

**Comment by jhammers15** [comment]
Can you remove the "Change Password" menu item from the Main Menu under Me too?

**Comment by guychapman** [comment]
Change password has been removed. Please test and comment

**Comment by jhammers15** [comment]
Guy,

It’s still there.
[cid:image001.png@01D114F3.B2A8CB30]

John Hammersmith

Enterprise Solution Architect

P 08 8306 6967   M 0413 330 390
E john.hammersmith@stjohnsa.com.au<mailto:john.hammersmith@stjohnsa.com.au>


St John Ambulance Australia SA Inc.

85 Edmund Ave UNLEY SA 5061
1300 360 455  |  stjohnsa.com.au<http://www.stjohnsa.com.au/>

**Comment by guychapman** [comment]
Yep - sorry, hadn't pushed the update through from my local computer

**Comment by jhammers15** [comment]
Guy, This is good to move to production now. Thanks John
