### ISSUE TITLE
Add New Division to SA DEMS - EPEG

### ISSUE THREAD

**Issue by jhammers15** [St-John-NSW/DEMS#40]
Please create a brand new Divsion in the SA DEMS system called EPEG

**Comment by guychapman** [comment]
Hi,

What region does this fall under?

Sent by Outlook<http://taps.io/outlookmobile> for Android



On Wed, Nov 4, 2015 at 6:30 PM -0800, "John Hammersmith" <notifications@github.com<mailto:notifications@github.com>> wrote:


Please create a brand new Divsion in the SA DEMS system called EPEG

-

**Comment by guychapman** [comment]
State Office

**Comment by jhammers15** [comment]
Guy,

In fact I have a need for another one to create under State as well – Commercial Training Division.


John Hammersmith

Enterprise Solution Architect

P 08 8306 6967   M 0413 330 390
E john.hammersmith@stjohnsa.com.au<mailto:john.hammersmith@stjohnsa.com.au>


St John Ambulance Australia SA Inc.

85 Edmund Ave UNLEY SA 5061
1300 360 455  |  stjohnsa.com.au<http://www.stjohnsa.com.au/>
